<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-KTHKFE5" failures="1" tests="9" name="tests.login_test" time="24.644" errors="0" timestamp="2021-01-04T04:29:49 IST" skipped="0">
  <testcase classname="tests.login_test" name="getResponseTime" time="1.786"/>
  <system-out/>
  <testcase classname="tests.login_test" name="t03_loginFailedNoMatchAssert" time="1.234">
    <failure message="expected [Sorry! Epic sadface: Username and password do not match any user in this service] but found [Epic sadface: Username and password do not match any user in this service]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Sorry! Epic sadface: Username and password do not match any user in this service] but found [Epic sadface: Username and password do not match any user in this service]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at tests.login_test.t03_loginFailedNoMatchAssert(login_test.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- t03_loginFailedNoMatchAssert -->
  <system-out/>
  <testcase classname="tests.login_test" name="t01_loginFailedFromTable" time="1.236"/>
  <system-out/>
  <testcase classname="tests.login_test" name="t01_loginFailedFromTable" time="1.225"/>
  <system-out/>
  <testcase classname="tests.login_test" name="getStatusCode" time="0.486"/>
  <system-out/>
  <testcase classname="tests.login_test" name="t01_loginFailedFromTable" time="1.540"/>
  <system-out/>
  <testcase classname="tests.login_test" name="t04_loginSucceed" time="14.607"/>
  <system-out/>
  <testcase classname="tests.login_test" name="t01_loginFailedFromTable" time="1.273"/>
  <system-out/>
  <testcase classname="tests.login_test" name="t02_loginFailedMatchAssert" time="1.257"/>
  <system-out/>
</testsuite> <!-- tests.login_test -->
